### ISSUE TITLE
6. Scrolling the world

### ISSUE THREAD

**Issue by pranaysashank** [MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift3#2]
**Update**
My bad, there's no error here. Xcode was messing with me.

**Old**
In the section **Ready to Rock and Scroll**, the SKNode found should be cast as SKSpriteNode
So
`scrollLayer = self.childNode(withName: "scrollLayer")`
to
`scrollLayer = self.childNode(withName: "scrollLayer") as! SKSpriteNode`

**Comment by dionlarson** [comment]
Thank you for the update!
